User.delete_all
Badge.delete_all
Recipe.delete_all
Ingredient.delete_all
Quantity.delete_all
Challenge.delete_all

user1 = User.create(name: 'Clark Kent', nickname: 'Supes', email: 'clark@kent.com', first_name: 'Clark', last_name: 'Kent', username:'supes', password:'123456789', exp_gained: 45)
user2 = User.create(name: 'Bruce Wayne', nickname: 'Batty', email: 'bruce@wayne.com', first_name: 'Bruce', last_name: 'Wayne', username:'batster', password:'123456789', exp_gained: 90)
user3 = User.create(name: 'Steve Rogers', nickname: 'Cap', email: 'steve@rogers.com', first_name: 'Steve', last_name: 'Rogers', username:'capn', password:'123456789', exp_gained: 150)
user4 = User.create(name: 'Anthony Stark', nickname: 'Tinman', email: 'tony@stark.com', first_name: 'Tony', last_name: 'Stark', username:'tinman', password:'123456789', exp_gained: 0)

badge1 = Badge.create(user_id:user1.id,badge_name: "Chop Master",badge_type: 1)
badge2 = Badge.create(user_id:user1.id,badge_name: "Mix Master",badge_type: 2)
badge3 = Badge.create(user_id:user1.id,badge_name: "Vegan Master",badge_type: 3)
badge4 = Badge.create(user_id:user2.id,badge_name: "Chop Master",badge_type: 1)
badge5 = Badge.create(user_id:user2.id,badge_name: "Mix Master",badge_type: 2)
badge6 = Badge.create(user_id:user2.id,badge_name: "Gluten Free Master",badge_type: 4)
badge7 = Badge.create(user_id:user2.id,badge_name: "Stir-fry Master",badge_type: 5)
badge8 = Badge.create(user_id:user2.id,badge_name: "Dessert Master",badge_type: 6)
badge9 = Badge.create(user_id:user2.id,badge_name: "Chef",badge_type: 7)
badge10 = Badge.create(user_id:user3.id,badge_name: "Chop Master",badge_type: 1)
badge11 = Badge.create(user_id:user3.id,badge_name: "Mix Master",badge_type: 2)
badge12 = Badge.create(user_id:user3.id,badge_name: "Vegan Master",badge_type: 3)
badge13 = Badge.create(user_id:user3.id,badge_name: "Stir-fry Master",badge_type: 5)
badge14 = Badge.create(user_id:user3.id,badge_name: "Dessert Master",badge_type: 6)
badge15 = Badge.create(user_id:user3.id,badge_name: "Chef",badge_type: 7)

ing1 = Ingredient.create(name: "Salt")
ing2 = Ingredient.create(name: "Black Pepper")
ing3 = Ingredient.create(name: "Tomato")
ing4 = Ingredient.create(name: "Lettuce")
ing5 = Ingredient.create(name: "Ginger")
ing6 = Ingredient.create(name: "Onion")
ing7 = Ingredient.create(name: "Penne")
ing8 = Ingredient.create(name: "Lime")
ing9 = Ingredient.create(name: "Feta Cheese")
ing10 = Ingredient.create(name: "Tortilla Wrap")
ing11 = Ingredient.create(name: "Avocado")
ing12 = Ingredient.create(name: "Red Pepper")
ing13 = Ingredient.create(name: "Tofu")
ing14 = Ingredient.create(name: "Broccoli")
ing15 = Ingredient.create(name: "Mushroom")
ing16 = Ingredient.create(name: "Chickpeas")
ing17 = Ingredient.create(name: "Rice")
ing18 = Ingredient.create(name: "Olive Oil")
ing19 = Ingredient.create(name: "Parsley")
ing20 = Ingredient.create(name: "Paprika")

recipe1 = Recipe.create(name: "Curried Quinoa", instructions: "cook well something something curried quinoa", video_url:"https://www.youtube.com/embed/Vr50GWUy0vo", cook_time:15, serving:2, course:"Appetizer", vegan:true, gluten_free:false, low_carb:false, exp_value:0, equipment:"pot,pan,knife", dish_image:"http://www.thegluttonousvegan.com/farm5.static.flickr.com/4034/4404190215_7730cbe9b7_o.jpg", ingredients_image:"http://thumbs.dreamstime.com/z/healthy-vegetarian-home-made-food-creative-cooking-concept-fresh-vegetables-chopped-salads-kitchen-wooden-utensils-top-53160960.jpg")
recipe2 = Recipe.create(name: "Chickpea Pancake", instructions: "cook well something something chickpea pancake", video_url:"https://www.youtube.com/embed/Vr50GWUy0vo", cook_time:15, serving:4, course:"Appetizer", vegan:false, gluten_free:true, low_carb:false, exp_value:90, equipment:"pot,pan,knife", dish_image:"http://www.bbcgoodfood.com/sites/default/files/tofu-main.jpg", ingredients_image:"http://thumbs.dreamstime.com/z/healthy-vegetarian-home-made-food-creative-cooking-concept-fresh-vegetables-chopped-salads-kitchen-wooden-utensils-top-53160960.jpg")
recipe3 = Recipe.create(name: "Chili Basil Tofu", instructions: "cook well something something chili basil tofu", video_url:"https://www.youtube.com/embed/Vr50GWUy0vo", cook_time:25, serving:6, course:"Appetizer", vegan:true, gluten_free:true, low_carb:true, exp_value:150, equipment:"bowl,spoon,fork,knife", dish_image:"http://www.theorangegroveclinic.co.uk/wp-content/uploads/2012/06/vegetarian-food.jpg", ingredients_image:"http://thumbs.dreamstime.com/z/healthy-vegetarian-home-made-food-creative-cooking-concept-fresh-vegetables-chopped-salads-kitchen-wooden-utensils-top-53160960.jpg")
recipe4 = Recipe.create(name: "Singapore Noodles", instructions: "cook well something something singapore nodles", video_url:"https://www.youtube.com/embed/Vr50GWUy0vo", cook_time:20, serving:2, course:"Main", vegan:false, gluten_free:true, low_carb:true, exp_value:45, equipment:"bowl,spoon,fork,knife", dish_image:"http://www.bbcgoodfood.com/sites/default/files/tofu-main.jpg", ingredients_image:"http://thumbs.dreamstime.com/z/healthy-vegetarian-home-made-food-creative-cooking-concept-fresh-vegetables-chopped-salads-kitchen-wooden-utensils-top-53160960.jpg")
recipe5 = Recipe.create(name: "Mexican Flautas", instructions: "cook well something something flautas", video_url:"https://www.youtube.com/embed/Vr50GWUy0vo", cook_time:30, serving:4, course:"Main", vegan:true, gluten_free:true, low_carb:false, exp_value:0, equipment:"none", dish_image:"https://i.ytimg.com/vi/FlS_3DcS6Q0/maxresdefault.jpg", ingredients_image:"http://thumbs.dreamstime.com/z/healthy-vegetarian-home-made-food-creative-cooking-concept-fresh-vegetables-chopped-salads-kitchen-wooden-utensils-top-53160960.jpg")
recipe6 = Recipe.create(name: "Spinach Jalapeno Pesto Penne", instructions: "cook well something something penne", video_url:"https://www.youtube.com/embed/Vr50GWUy0vo", cook_time:40, serving:6, course:"Main", vegan:false, gluten_free:false, low_carb:false, exp_value:60, equipment:"ladel,collander", dish_image:"http://40.media.tumblr.com/tumblr_mbc13to8PO1r6bchgo3_1280.jpg", ingredients_image:"http://thumbs.dreamstime.com/z/healthy-vegetarian-home-made-food-creative-cooking-concept-fresh-vegetables-chopped-salads-kitchen-wooden-utensils-top-53160960.jpg")
recipe7 = Recipe.create(name: "Japanese Okonomiyaki", instructions: "cook well something something okonomiyaki", video_url:"https://www.youtube.com/embed/Vr50GWUy0vo", cook_time:12, serving:2, course:"Main", vegan:true, gluten_free:true, low_carb:true, exp_value:15, equipment:"pan,whisk", dish_image:"https://s-media-cache-ak0.pinimg.com/736x/30/97/1e/30971e4805fce8f991cb7e4958d18351.jpg", ingredients_image:"http://thumbs.dreamstime.com/z/healthy-vegetarian-home-made-food-creative-cooking-concept-fresh-vegetables-chopped-salads-kitchen-wooden-utensils-top-53160960.jpg")
recipe8 = Recipe.create(name: "Tandoori Wraps", instructions: "cook well something something tandoori", video_url:"https://www.youtube.com/embed/Vr50GWUy0vo", cook_time:8, serving:4, course:"Dessert", vegan:false, gluten_free:false, low_carb:true, exp_value:90, equipment:"pot", dish_image:"http://40.media.tumblr.com/c3a50aeae6f0c9a3ef92cf9d1f1b8f6f/tumblr_muh4huYCLW1rj3wsho2_1280.png", ingredients_image:"http://thumbs.dreamstime.com/z/healthy-vegetarian-home-made-food-creative-cooking-concept-fresh-vegetables-chopped-salads-kitchen-wooden-utensils-top-53160960.jpg")
recipe9 = Recipe.create(name: "Hummus", instructions: "cook well something something hummus", video_url:"https://www.youtube.com/embed/Vr50GWUy0vo", cook_time:22, serving:6, course:"Dessert", vegan:true, gluten_free:false, low_carb:false, exp_value:30, equipment:"pan,bowl,knife,spoon,fork", dish_image:"https://emilyjensennutrition.files.wordpress.com/2013/01/vegetables-vegetarian-collage-favim-com-485200.jpg", ingredients_image:"http://thumbs.dreamstime.com/z/healthy-vegetarian-home-made-food-creative-cooking-concept-fresh-vegetables-chopped-salads-kitchen-wooden-utensils-top-53160960.jpg")
recipe10 = Recipe.create(name: "Sesame Peanut Noodles", instructions: "cook well something something peanut noodles", video_url:"https://www.youtube.com/embed/Vr50GWUy0vo", cook_time:25, serving:1, course:"Dessert", vegan:false, gluten_free:false, low_carb:false, exp_value:0, equipment:"none", dish_image:"http://selagi.com/wp-content/uploads/2014/08/vegetarian-recipes-easy-dinner-healthy.jpg", ingredients_image:"http://thumbs.dreamstime.com/z/healthy-vegetarian-home-made-food-creative-cooking-concept-fresh-vegetables-chopped-salads-kitchen-wooden-utensils-top-53160960.jpg")


qt1 = Quantity.create(ingredient_id: ing1.id,recipe_id: recipe1.id,measurement:"1 cup")
qt2 = Quantity.create(ingredient_id: ing2.id,recipe_id: recipe1.id,measurement:"100 grams")
qt3 = Quantity.create(ingredient_id: ing3.id,recipe_id: recipe1.id,measurement:"3/4 cup")
qt4 = Quantity.create(ingredient_id: ing4.id,recipe_id: recipe1.id,measurement:"1 Tablespoon")
qt5 = Quantity.create(ingredient_id: ing5.id,recipe_id: recipe1.id,measurement:"1/2 Teaspoon")
qt6 = Quantity.create(ingredient_id: ing6.id,recipe_id: recipe2.id,measurement:"1 cup")
qt7 = Quantity.create(ingredient_id: ing7.id,recipe_id: recipe2.id,measurement:"100 grams")
qt8 = Quantity.create(ingredient_id: ing8.id,recipe_id: recipe2.id,measurement:"3/4 cup")
qt9 = Quantity.create(ingredient_id: ing9.id,recipe_id: recipe2.id,measurement:"1 Tablespoon")
qt10 = Quantity.create(ingredient_id: ing10.id,recipe_id: recipe2.id,measurement:"1/2 Teaspoon")
qt11 = Quantity.create(ingredient_id: ing11.id,recipe_id: recipe2.id,measurement:"1 cup")
qt12 = Quantity.create(ingredient_id: ing12.id,recipe_id: recipe2.id,measurement:"100 grams")
qt13 = Quantity.create(ingredient_id: ing13.id,recipe_id: recipe2.id,measurement:"3/4 cup")
qt14 = Quantity.create(ingredient_id: ing14.id,recipe_id: recipe2.id,measurement:"1 Tablespoon")
qt15 = Quantity.create(ingredient_id: ing15.id,recipe_id: recipe2.id,measurement:"1/2 Teaspoon")
qt16 = Quantity.create(ingredient_id: ing16.id,recipe_id: recipe3.id,measurement:"1 cup")
qt17 = Quantity.create(ingredient_id: ing17.id,recipe_id: recipe3.id,measurement:"100 grams")
qt18 = Quantity.create(ingredient_id: ing18.id,recipe_id: recipe3.id,measurement:"3/4 cup")
qt19 = Quantity.create(ingredient_id: ing19.id,recipe_id: recipe3.id,measurement:"1 Tablespoon")
qt20 = Quantity.create(ingredient_id: ing20.id,recipe_id: recipe3.id,measurement:"1/2 Teaspoon")
qt21 = Quantity.create(ingredient_id: ing1.id,recipe_id: recipe3.id,measurement:"1 cup")
qt22 = Quantity.create(ingredient_id: ing2.id,recipe_id: recipe3.id,measurement:"100 grams")
qt23 = Quantity.create(ingredient_id: ing3.id,recipe_id: recipe3.id,measurement:"3/4 cup")
qt24 = Quantity.create(ingredient_id: ing4.id,recipe_id: recipe3.id,measurement:"1 Tablespoon")
qt25 = Quantity.create(ingredient_id: ing5.id,recipe_id: recipe3.id,measurement:"1/2 Teaspoon")
qt26 = Quantity.create(ingredient_id: ing16.id,recipe_id: recipe4.id,measurement:"1 cup")
qt27 = Quantity.create(ingredient_id: ing17.id,recipe_id: recipe4.id,measurement:"100 grams")
qt28 = Quantity.create(ingredient_id: ing18.id,recipe_id: recipe4.id,measurement:"3/4 cup")
qt29 = Quantity.create(ingredient_id: ing19.id,recipe_id: recipe4.id,measurement:"1 Tablespoon")
qt30 = Quantity.create(ingredient_id: ing20.id,recipe_id: recipe4.id,measurement:"1/2 Teaspoon")
qt31 = Quantity.create(ingredient_id: ing1.id,recipe_id: recipe4.id,measurement:"1 cup")
qt32 = Quantity.create(ingredient_id: ing2.id,recipe_id: recipe4.id,measurement:"100 grams")
qt33 = Quantity.create(ingredient_id: ing3.id,recipe_id: recipe4.id,measurement:"3/4 cup")
qt34 = Quantity.create(ingredient_id: ing4.id,recipe_id: recipe4.id,measurement:"1 Tablespoon")
qt35 = Quantity.create(ingredient_id: ing5.id,recipe_id: recipe4.id,measurement:"1/2 Teaspoon")
qt36 = Quantity.create(ingredient_id: ing20.id,recipe_id: recipe5.id,measurement:"1/2 Teaspoon")
qt37 = Quantity.create(ingredient_id: ing1.id,recipe_id: recipe5.id,measurement:"1 cup")
qt38 = Quantity.create(ingredient_id: ing2.id,recipe_id: recipe5.id,measurement:"100 grams")
qt39 = Quantity.create(ingredient_id: ing3.id,recipe_id: recipe5.id,measurement:"3/4 cup")
qt40 = Quantity.create(ingredient_id: ing4.id,recipe_id: recipe5.id,measurement:"1 Tablespoon")
qt41 = Quantity.create(ingredient_id: ing5.id,recipe_id: recipe5.id,measurement:"1/2 Teaspoon")
qt42 = Quantity.create(ingredient_id: ing6.id,recipe_id: recipe5.id,measurement:"1 cup")
qt43 = Quantity.create(ingredient_id: ing17.id,recipe_id: recipe5.id,measurement:"100 grams")
qt44 = Quantity.create(ingredient_id: ing18.id,recipe_id: recipe5.id,measurement:"3/4 cup")
qt45 = Quantity.create(ingredient_id: ing19.id,recipe_id: recipe5.id,measurement:"1 Tablespoon")
qt46 = Quantity.create(ingredient_id: ing9.id,recipe_id: recipe5.id,measurement:"1/2 Teaspoon")
qt47 = Quantity.create(ingredient_id: ing10.id,recipe_id: recipe5.id,measurement:"1 cup")
qt48 = Quantity.create(ingredient_id: ing12.id,recipe_id: recipe5.id,measurement:"100 grams")
qt49 = Quantity.create(ingredient_id: ing13.id,recipe_id: recipe5.id,measurement:"3/4 cup")
qt50 = Quantity.create(ingredient_id: ing14.id,recipe_id: recipe5.id,measurement:"1 Tablespoon")
qt51 = Quantity.create(ingredient_id: ing15.id,recipe_id: recipe5.id,measurement:"1/2 Teaspoon")
qt52 = Quantity.create(ingredient_id: ing1.id,recipe_id: recipe6.id,measurement:"1 cup")
qt53 = Quantity.create(ingredient_id: ing2.id,recipe_id: recipe6.id,measurement:"100 grams")
qt54 = Quantity.create(ingredient_id: ing3.id,recipe_id: recipe6.id,measurement:"3/4 cup")
qt55 = Quantity.create(ingredient_id: ing4.id,recipe_id: recipe6.id,measurement:"1 Tablespoon")
qt56 = Quantity.create(ingredient_id: ing5.id,recipe_id: recipe6.id,measurement:"1/2 Teaspoon")
qt57 = Quantity.create(ingredient_id: ing6.id,recipe_id: recipe6.id,measurement:"1 cup")
qt58 = Quantity.create(ingredient_id: ing1.id,recipe_id: recipe7.id,measurement:"1 cup")
qt59 = Quantity.create(ingredient_id: ing2.id,recipe_id: recipe7.id,measurement:"100 grams")
qt60 = Quantity.create(ingredient_id: ing3.id,recipe_id: recipe7.id,measurement:"3/4 cup")
qt61 = Quantity.create(ingredient_id: ing4.id,recipe_id: recipe7.id,measurement:"1 Tablespoon")
qt62 = Quantity.create(ingredient_id: ing1.id,recipe_id: recipe8.id,measurement:"1 cup")
qt63 = Quantity.create(ingredient_id: ing2.id,recipe_id: recipe8.id,measurement:"100 grams")
qt64 = Quantity.create(ingredient_id: ing3.id,recipe_id: recipe8.id,measurement:"3/4 cup")
qt65 = Quantity.create(ingredient_id: ing4.id,recipe_id: recipe8.id,measurement:"1 Tablespoon")
qt66 = Quantity.create(ingredient_id: ing5.id,recipe_id: recipe8.id,measurement:"1/2 Teaspoon")
qt67 = Quantity.create(ingredient_id: ing6.id,recipe_id: recipe8.id,measurement:"1 cup")
qt68 = Quantity.create(ingredient_id: ing1.id,recipe_id: recipe9.id,measurement:"1 cup")
qt69 = Quantity.create(ingredient_id: ing2.id,recipe_id: recipe9.id,measurement:"100 grams")
qt70 = Quantity.create(ingredient_id: ing3.id,recipe_id: recipe9.id,measurement:"3/4 cup")
qt71 = Quantity.create(ingredient_id: ing4.id,recipe_id: recipe9.id,measurement:"1 Tablespoon")
qt72 = Quantity.create(ingredient_id: ing5.id,recipe_id: recipe9.id,measurement:"1/2 Teaspoon")
qt73 = Quantity.create(ingredient_id: ing6.id,recipe_id: recipe9.id,measurement:"1 cup")
qt74 = Quantity.create(ingredient_id: ing1.id,recipe_id: recipe10.id,measurement:"1 cup")
qt75 = Quantity.create(ingredient_id: ing2.id,recipe_id: recipe10.id,measurement:"100 grams")
qt76 = Quantity.create(ingredient_id: ing3.id,recipe_id: recipe10.id,measurement:"3/4 cup")
qt77 = Quantity.create(ingredient_id: ing4.id,recipe_id: recipe10.id,measurement:"1 Tablespoon")
qt78 = Quantity.create(ingredient_id: ing5.id,recipe_id: recipe10.id,measurement:"1/2 Teaspoon")
qt79 = Quantity.create(ingredient_id: ing6.id,recipe_id: recipe10.id,measurement:"1 cup")



